theme: jekyll-theme-cayman
title: temporalis
description: go package that provides additional functionality for working with time values beyond what is provided by the standard time package. it includes all of the functions from the time package as well as additional functions for formatting and parsing time values.
